### ISSUE TITLE
Add ability to use multirun with venvs

### ISSUE THREAD

**Issue by josham** [pawamoy/pdm-multirun#1]
It doesn't seem possible to use `pdm multirun` to run a command across multiple venvs.

```
$ pdm venv list
Virtualenvs created with this project:

*  3.7: /home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.7
-  3.8: /home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.8
-  3.9: /home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.9
-  3.10: /home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.10
-  3.11: /home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.11
```

Would be nice to be able to do something like:

```
$ pdm multirun --venvs 3.7,3.8 which python
/home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.7/bin/python
/home/foo/.local/share/pdm/venvs/pdm-test-LMFOy7kN-3.8/bin/python
```

I looked a bit at `plugin.py` and it seems like setting the `venv` argument in the call to `actions.do_use` would do the trick.

**Comment by pawamoy** [comment]
Hello, thanks for the report / feature request. Would you like to contribute the feature? I'll gladly review a pull request :slightly_smiling_face:

**Comment by pawamoy** [comment]
This was implemented in https://github.com/pawamoy/pdm-multirun/commit/f2b838145624ecaa245681e5e4e9ef15834f55a3
