### ISSUE TITLE
bug: multirun produce error with pdm 2.16

### ISSUE THREAD

**Issue by natir** [pawamoy/pdm-multirun#11]
### Description of the bug

After update pdm to version `2.16.1` run pdm generate this error: 
```
ERROR: Failed to load plugin multirun=pdm_multirun.plugin:multirun: cannot import name 'Project'
from 'pdm.cli.commands.run'
```

### To Reproduce

Just add pdm-multirun in tool.pdm.plugins

### Environment information

```bash
- __System__: Linux-6.9.5-100.fc39.x86_64-x86_64-with-glibc2.38
- __Python__: cpython 3.12.3
- __Environment variables__:
  - `PYTHONPATH`: `$HOME/.local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/pep582`
- __Installed packages__:
  - `pdm-multirun` v0.0.0
```

**Comment by pawamoy** [comment]
Hi @natir, thanks for the report! Would you like to send a PR? I suppose it's just a matter of importing `Project` from somewhere else.
