### ISSUE TITLE
Option to use venvs using environment variable

### ISSUE THREAD

**Issue by DomWeldon** [pawamoy/pdm-multirun#4]
**Is your feature request related to a problem? Please describe.**
Love the plugin, just had an issue where my virtual environments were named after their python versions (e.g., 3.8.17, 3.9.17) and I found that I kept getting muddled between venvs and PEP 582 style environments because I'd forget to add the -e flag to my commands.

**Describe the solution you'd like**
Suggesting a new feature where there is an environment variable, PDM_MULTIRUN_USE_VENVS which when set to 1 will use virtual environments by default.

**Comment by DomWeldon** [comment]
Closed by https://github.com/pawamoy/pdm-multirun/pull/3

**Comment by pawamoy** [comment]
Implemented in #3, thanks :slightly_smiling_face:

**Comment by pawamoy** [comment]
Released as 1.0.0 :slightly_smiling_face:
